from __future__ import annotations

import json
from pathlib import Path

import pytest


GOLDEN = json.loads(
    (Path(__file__).parent / "golden" / "ieee39-pandapower-3.4.0.json").read_text(encoding="utf-8")
)["ieee39"]
N_MINUS_ONE_LOADING_REL_TOL = 1e-12
N_MINUS_ONE_LOADING_ABS_TOL_PERCENT = 1e-9


def _line_ref(grid, context_ref: str, index: int) -> str:
    result = grid.call(
        "model.element.get",
        {
            "context_ref": context_ref,
            "kind": "line",
            "namespace": "pandapower_index",
            "identifier": str(index),
        },
    )
    return str(result["element"]["asset_ref"])


def test_n_minus_one_preserves_partial_scenario_failure(grid, context_ref: str, line_refs: list[str]) -> None:
    grid.engine.non_convergent_outages.add(1)

    result = grid.call(
        "analysis.contingency.n_minus_one.run",
        {"context_ref": context_ref, "branch_refs": line_refs[:2]},
    )

    assert result["status"] == "partial"
    assert "policy" not in result
    assert [item["status"] for item in result["scenarios"]] == ["succeeded", "non_converged"]
    assert all(item["evidence_ref"].startswith("evidence:sha256:") for item in result["scenarios"])


def test_n_minus_one_uses_stable_branch_ref_and_reports_overload_evidence(grid, context_ref: str) -> None:
    line_11_ref = _line_ref(grid, context_ref, 11)

    result = grid.call(
        "analysis.contingency.n_minus_one.run",
        {"context_ref": context_ref, "branch_refs": [line_11_ref]},
    )

    assert result["status"] == "succeeded"
    assert result["result_ref"].startswith("result:sha256:")
    assert len(result["scenarios"]) == 1
    scenario = result["scenarios"][0]
    assert scenario["branch_ref"] == line_11_ref
    assert scenario["status"] == "succeeded"
    assert scenario["converged"] is True
    # Golden values are generated by pandapower 3.4.0 on IEEE-39; keep tolerance narrow for deterministic drift.
    assert scenario["max_loading_percent"] == pytest.approx(
        GOLDEN["line_11_outage_max_loading_percent"],
        rel=N_MINUS_ONE_LOADING_REL_TOL,
        abs=N_MINUS_ONE_LOADING_ABS_TOL_PERCENT,
    )
    overloaded_line_indices = [
        item["pandapower_index"] for item in scenario["violations"] if item["kind"] == "line_overload"
    ]
    assert overloaded_line_indices == GOLDEN["line_11_outage_overloaded_line_indices"]
    threshold_violations = [item for item in scenario["violations"] if item["kind"] != "non_convergence"]
    assert all(item["constraint_ref"].startswith("constraint:sha256:") for item in threshold_violations)
    assert all(item["constraint_source"] == "model" for item in threshold_violations)

    loaded = grid.call("evidence.get", {"evidence_ref": scenario["evidence_ref"]})
    assert loaded["document"]["evidence_type"] == "contingency_scenario"
    assert loaded["document"]["facts"]["min_vm_pu"] == pytest.approx(
        scenario["min_vm_pu"]
    )
    assert loaded["document"]["facts"]["constraint_evaluation"] == scenario[
        "constraint_evaluation"
    ]


def test_n_minus_one_rejects_uncontracted_threshold_argument(grid, context_ref: str, line_refs: list[str]) -> None:
    error = grid.call_error(
        "analysis.contingency.n_minus_one.run",
        {"context_ref": context_ref, "branch_refs": line_refs[:1], "loading_limit": 100.0},
    )

    assert error.code == "invalid_arguments"
