from __future__ import annotations

import json
from pathlib import Path

import pytest


GOLDEN = json.loads(
    (Path(__file__).parent / "golden" / "ieee39-pandapower-3.4.0.json").read_text(encoding="utf-8")
)["ieee39"]
AC_LOSS_REL_TOL = 1e-12
AC_LOSS_ABS_TOL_MW = 1e-9


def _result_document_path(result_ref: str, root: Path) -> Path:
    return root / "evidence" / "results" / f"powerflow-{result_ref.removeprefix('result:sha256:')}.json"


def test_ac_powerflow_records_effective_solver_and_evidence(grid, context_ref: str) -> None:
    result = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})

    assert result["converged"] is True
    assert result["solver"]["profile"] == "ac-default-v1"
    assert result["solver"]["algorithm"] == "nr"
    assert result["total_active_loss"]["unit"] == "MW"
    assert result["result_ref"].startswith("result:sha256:")
    assert result["evidence_refs"]


def test_ac_powerflow_persists_complete_normalized_result(grid, context_ref: str) -> None:
    result = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})
    document = json.loads(_result_document_path(str(result["result_ref"]), grid.workspace.root).read_text(encoding="utf-8"))

    assert document["result_ref"] == result["result_ref"]
    assert document["context_ref"] == context_ref
    assert document["solver"]["profile"] == "ac-default-v1"
    assert document["convergence"]["converged"] is True
    # Golden values are generated by pandapower 3.4.0 on IEEE-39; keep tolerance narrow for deterministic drift.
    assert document["losses"]["total_active_loss"]["value"] == pytest.approx(
        GOLDEN["total_active_loss_mw"],
        rel=AC_LOSS_REL_TOL,
        abs=AC_LOSS_ABS_TOL_MW,
    )
    assert document["bus_results"]
    assert document["branch_results"]
    assert document["transformer_results"]
    assert document["generator_results"]
    assert document["load_results"]
    assert document["external_grid_results"]
    assert document["branch_results"][0]["asset_ref"].startswith("asset:line:sha256:")
    assert {"loading_percent", "p_from_mw", "p_to_mw", "pl_mw"} <= set(document["branch_results"][0])


def test_branch_ranking_reads_persisted_result_without_rerunning_ac(grid, context_ref: str) -> None:
    powerflow = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})
    assert grid.engine.ac_run_count == 1

    ranking = grid.call(
        "result.branches.rank",
        {
            "result_ref": powerflow["result_ref"],
            "metric": "loading_percent",
            "direction": "descending",
            "limit": 5,
            "element_kind": "line",
        },
    )

    assert grid.engine.ac_run_count == 1
    assert ranking["result_ref"] == powerflow["result_ref"]
    assert ranking["metric"] == "loading_percent"
    assert ranking["metric_unit"] == "percent"
    assert [item["pandapower_index"] for item in ranking["branches"]] == GOLDEN["top5_line_indices"]
    assert all(item["branch_ref"].startswith("asset:line:sha256:") for item in ranking["branches"])


def test_branch_ranking_rejects_tampered_result_document(grid, context_ref: str) -> None:
    powerflow = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})
    path = _result_document_path(str(powerflow["result_ref"]), grid.workspace.root)
    document = json.loads(path.read_text(encoding="utf-8"))
    document["branch_results"][0]["loading_percent"] = 9999
    path.write_text(json.dumps(document), encoding="utf-8")

    error = grid.call_error(
        "result.branches.rank",
        {
            "result_ref": powerflow["result_ref"],
            "metric": "loading_percent",
            "direction": "descending",
            "limit": 1,
        },
    )

    assert error.code == "result_integrity_failed"
    assert error.phase == "resolve"


def test_branch_ranking_rejects_invalid_json_result_document(grid, context_ref: str) -> None:
    powerflow = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})
    _result_document_path(str(powerflow["result_ref"]), grid.workspace.root).write_text("{", encoding="utf-8")

    error = grid.call_error(
        "result.branches.rank",
        {
            "result_ref": powerflow["result_ref"],
            "metric": "loading_percent",
            "direction": "descending",
            "limit": 1,
        },
    )

    assert error.code == "result_integrity_failed"
    assert error.phase == "resolve"


def test_branch_ranking_rejects_non_utf8_result_document(grid, context_ref: str) -> None:
    powerflow = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})
    _result_document_path(str(powerflow["result_ref"]), grid.workspace.root).write_bytes(b"\xff\xfe\xfa")

    error = grid.call_error(
        "result.branches.rank",
        {
            "result_ref": powerflow["result_ref"],
            "metric": "loading_percent",
            "direction": "descending",
            "limit": 1,
        },
    )

    assert error.code == "result_integrity_failed"
    assert error.phase == "resolve"


def test_branch_ranking_rejects_result_document_without_result_ref(grid, context_ref: str) -> None:
    powerflow = grid.call("analysis.powerflow.ac.run", {"context_ref": context_ref})
    path = _result_document_path(str(powerflow["result_ref"]), grid.workspace.root)
    document = json.loads(path.read_text(encoding="utf-8"))
    del document["result_ref"]
    path.write_text(json.dumps(document), encoding="utf-8")

    error = grid.call_error(
        "result.branches.rank",
        {
            "result_ref": powerflow["result_ref"],
            "metric": "loading_percent",
            "direction": "descending",
            "limit": 1,
        },
    )

    assert error.code == "result_integrity_failed"
    assert error.phase == "resolve"


def test_branch_ranking_unknown_result_is_read_only(grid) -> None:
    error = grid.call_error(
        "result.branches.rank",
        {
            "result_ref": "result:sha256:" + "1" * 64,
            "metric": "loading_percent",
            "direction": "descending",
            "limit": 1,
        },
    )

    assert error.code == "unknown_result"
    assert error.phase == "resolve"
    assert not (grid.workspace.root / "evidence").exists()
